In [ ]:
# Tensor nothing but a data structure
# Tensor basically multidimensional numerical data- container।

In [2]:
import torch
print(torch.__version__)

2.11.0+cu128


In [ ]:
# 0 Dimensional
x = torch.tensor(5)
x.shape

torch.Size([])

In [ ]:
# 1D-Vector
x = torch.tensor([1, 2, 3, 4])
x.shape

torch.Size([4])

In [ ]:
# 2D-Matrix
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])
x.shape

torch.Size([2, 3])

In [ ]:
# 3D Tensor
x=torch.tensor([
  [
    [1,2],
    [3,4]
  ],

  [
    [5,6],
    [7,8]
  ]
])
x.shape

torch.Size([2, 2, 2])

In [ ]:
# Check device
if torch.cuda.is_available():
    print('CUDA is available')
    device=torch.device('cuda')
    print(device)
else:
    print('CUDA is not available')
    device=torch.device('cpu')
    print(device)

CUDA is not available
cpu


In [ ]:
# Creating a tensor
# using empty function
a=torch.empty(4,2)
print(a)
type(a)

tensor([[5.1346e-08, 0.0000e+00],
        [1.9491e-08, 0.0000e+00],
        [1.3563e-19, 1.3563e-19],
        [2.7915e+20, 1.9435e-19]])


torch.Tensor

In [ ]:
# Using zeros
b=torch.zeros(4,2)
print(b)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [ ]:
# using ones
c=torch.ones(4,2)
print(c)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


In [ ]:
# Using rand function
d=torch.rand(4,2)
print(d)

tensor([[0.9584, 0.7444],
        [0.2656, 0.8040],
        [0.9775, 0.2733],
        [0.7503, 0.6173]])


In [ ]:
# Using tensor
e=torch.tensor([[1,2,3,4], [5,6,7,8]])
print(e)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [ ]:
# Tensor shape
f=torch.tensor([[1,2,3,4], [5,6,7,8]])
f.shape

torch.Size([2, 4])

In [ ]:
# Create a new tensor liske f shape
torch.empty_like(f)

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831,
         7954801838398993778],
        [2459029315949324647, 3474075647955515187, 7292503399645603117,
         3256494168812119602]])

In [ ]:
torch.ones_like(f)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])

In [ ]:
torch.zeros_like(f)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])

In [ ]:
# Tensor data type
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# Find data type
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
# convert type using to function
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
# Mathematical Operation

In [ ]:
# Scaler oparations
x=torch.rand(2,3)
x

tensor([[0.3338, 0.3442, 0.1080],
        [0.7137, 0.7805, 0.6575]])

In [ ]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.1114, 0.1185, 0.0117],
        [0.5093, 0.6092, 0.4322]])

In [ ]:
# Elementwise operation
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.3827, 0.8028, 0.7838],
        [0.8177, 0.9349, 0.8602]])
tensor([[0.4876, 0.7763, 0.7722],
        [0.9845, 0.8653, 0.7714]])


In [ ]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.3827, 0.0265, 0.0116],
        [0.8177, 0.0696, 0.0888]])

In [ ]:
# Some another feature
c = torch.tensor([1, -2, 3, -4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# Reduction operation
z=torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
z

tensor([[9., 7., 7.],
        [5., 6., 4.]])

In [ ]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([10, 26])

In [ ]:
# Mean
torch.mean(z)

tensor(6.3333)

In [ ]:
# median
torch.median(z)

tensor(6.)

In [ ]:
# max and min
torch.max(z)
torch.min(z)

tensor(4.)

In [ ]:
# standard deviation
torch.std(z)

tensor(1.7512)

In [ ]:
# variance
torch.var(z)

tensor(3.0667)

In [ ]:
# argmax
torch.argmax(z)

tensor(0)

In [ ]:
# argmin
torch.argmin(z)

tensor(5)

In [3]:
# Matrix Operation
x=torch.randint(0,10, (2,3))
y=torch.randint(0,10, (3,2))
x,y

(tensor([[3, 6, 8],
         [9, 6, 7]]),
 tensor([[4, 6],
         [0, 8],
         [9, 5]]))

In [4]:
# Matrix Multiplication
m=torch.matmul(x,y)
m

tensor([[ 84, 106],
        [ 99, 137]])

In [6]:
# Dor product
x1=torch.tensor([1,2,3])
y1=torch.tensor([4,5,6])
d=torch.dot(x1,y1)
d

tensor(32)

In [7]:
# Comparison operation
# greater than
x1 >y1
# less than
x1 < y1
# equal to
x1 == y1
# not equal to
x1 != y1
# greater than equal to
x1 >=y1
# less than equal to
x1 <=y1

tensor([True, True, True])

In [8]:
# Special function
X=torch.randint(0,10, (3,2), dtype=torch.float32)
X

tensor([[7., 3.],
        [1., 8.],
        [7., 7.]])

In [9]:
# Log
torch.log( X)

tensor([[1.9459, 1.0986],
        [0.0000, 2.0794],
        [1.9459, 1.9459]])

In [10]:
# Exponential
torch.exp(X)

tensor([[1.0966e+03, 2.0086e+01],
        [2.7183e+00, 2.9810e+03],
        [1.0966e+03, 1.0966e+03]])

In [11]:
# Sigmoid
torch.sigmoid(X)

tensor([[0.9991, 0.9526],
        [0.7311, 0.9997],
        [0.9991, 0.9991]])

In [13]:
# sqrt
torch.sqrt(X)

tensor([[2.6458, 1.7321],
        [1.0000, 2.8284],
        [2.6458, 2.6458]])

In [14]:
# Softmax
torch.softmax(X, dim=0)

tensor([[0.4994, 0.0049],
        [0.0012, 0.7275],
        [0.4994, 0.2676]])

In [15]:
# Relu
torch.relu(X)

tensor([[7., 3.],
        [1., 8.],
        [7., 7.]])

In [3]:
# peform tensor operation at GPU
# Check GPU available or Not
torch.cuda.is_available()

True

In [4]:
# Create a device variable
device=torch.device('cuda')

In [6]:
# Create a tensor inside GPU
z=torch.randint(0,10, (3,2), device=device)
z

tensor([[0, 1],
        [5, 4],
        [8, 6]], device='cuda:0')

In [10]:
# move existing tensor to gpu from cpu
z1=torch.randint(0,10, (3,2))
z1
c=z1.to(device=device)
c

tensor([[6, 3],
        [2, 0],
        [0, 3]], device='cuda:0')

In [11]:
# Comparison of matrix maltiplication (cpu/GPU)
import time

# Define the matrix size
size=1000

# Creates matrix on cpu
matrix_cpu1=torch.randn(size, size)
matrix_cpu2=torch.randn(size, size)

# Creates matrix on gpu
matrix_gpu1=matrix_cpu1.to(device)
matrix_gpu2=matrix_cpu2.to(device)

# Measure the time on cpu
start_time_cpu=time.time()
result_cpu=torch.matmul(matrix_cpu1, matrix_cpu2)  # Matrix multiplication on cpu
cpu_timw=time.time()-start_time_cpu
print(f"Time on cpu: {cpu_timw:4f} seconds")

# Move matrix to gpu
matrix_gpu1=matrix_gpu1.to(device)
matrix_gpu2=matrix_gpu2.to(device)

# Measure the time on gpu
start_time_gpu=time.time()
result_gpu=torch.matmul(matrix_gpu1, matrix_gpu2)  # matrix multiplication on gpu
gpu_time=time.time()-start_time_gpu

print(f"Time on gpu: {gpu_time:4f} seconds")


Time on cpu: 0.060346 seconds
Time on gpu: 0.135138 seconds
